apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    version: "v2.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: gunadhya/testappv2image
          ports:
            - name: http
              containerPort: 80